ALTER TABLE Users
DROP CONSTRAINT PK_User_IdAndUsername

ALTER TABLE Users
ADD CONSTRAINT PK_Id PRIMARY KEY (Id)

ALTER TABLE Users
ADD CONSTRAINT CHK_Username_Length CHECK (DATALENGTH(Username) >= 3)